spring.application.name=marketplace-mps-api
spring.config.import=optional:file:.env[properties]

# atualiza as tabelas automaticamente com base nas entidades
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true 

# configuração de conexão com o banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/dev_ominimarket
spring.datasource.username=postgres
spring.datasource.password=postgres
